// import './globals.css';
import React from "react"
import { cookies } from 'next/headers';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import AppSidebar from "@/components/Layout/app-sidebar";
import Header from "@/components/Layout/header";

export const metadata = {
    title: 'Shift Dashboard',
    description: 'Generated by Riwa',
}


export default async function RootLayout({
    children,
}:{
    children: React.ReactNode
}) {
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get('sidebar:state')?.value === 'true';

    return(
        <html lang="en">
            <body>
            <SidebarProvider defaultOpen={defaultOpen}>
                <AppSidebar />
                    <SidebarInset>
                    <Header />
                    {children}
                </SidebarInset>
            </SidebarProvider>
            </body>
        </html>
    )
}